version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "localhost: 127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka-host
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "localhost: 127.0.0.1"

  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.1
    hostname: sr-host
    ports:
      - 9081:9081
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:9081
    extra_hosts:
      - "localhost: 127.0.0.1"

  kafka-quickstart-producer:
    build: .
    image: kafka-quickstart-with-docker:1.0-SNAPSHOT
    command: ["java", "-cp", "/app/kafka-quickstart-with-docker-1.0-SNAPSHOT-jar-with-dependencies.jar", "com.trantorinc.kafkaquickstart.producers.OrderProducer", "orders" ]
    depends_on:
      - schema-registry

  kafka-quickstart-consumer:
    build: .
    image: kafka-quickstart-with-docker:1.0-SNAPSHOT
    command: [ "java", "-cp", "/app/kafka-quickstart-with-docker-1.0-SNAPSHOT-jar-with-dependencies.jar", "com.trantorinc.kafkaquickstart.consumers.OrderConsumer", "orders" ]
    depends_on:
      - kafka-quickstart-producer